apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    app: portal-noticias
spec:
  containers:
  - name: portal-noticias-contaoner
    image: aluracursos/portal-noticias:1
    ports:
      - containerPort: 80
